name: app
description: Application for wallpapers and images
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  lottie: ^2.4.0
  retrofit: ^4.0.1
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  image_downloader:
    git:
      url: https://github.com/ko2ic/image_downloader
  json_annotation: ^4.8.1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  retrofit_generator: ^7.0.1+1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/svg/